Repository AgileVentures/LocalSupport, pull requests merged in 2018-03, with the labels that each got.

#633 refactor users and registration controllers
  app/controllers/application_controller.rb
  app/controllers/registrations_controller.rb
  app/controllers/users_controller.rb
Labels: Refactor, ready-for-merge

#650 Remove Pages Helper
  app/helpers/pages_helper.rb
Labels: dev-chore

#654 fix incoming nil coords
  app/services/import_do_it_volunteer_opportunities.rb
  app/services/import_reach_skills_volunteer_opportunities.rb
  features/step_definitions/map_steps.rb
  features/vcr_cassettes/As_a_member_of_the_public/Imported_doit_volunteer_ops_with_nil_coords_are_assigned_default_coords.yml
  features/vcr_cassettes/As_a_member_of_the_public/Imported_reachskills_volunteer_ops_with_nil_coords_are_assigned_default_coords.yml
  features/volunteer_opportunities/map_volunteer_opportunities.feature
Labels: enhancement

#558 Search local events
  app/controllers/events_controller.rb
  app/models/event.rb
  app/views/events/_event.html.erb
  app/views/events/index.html.erb
  config/initializers/strings.rb
  db/seeds.rb
  features/events/search_local_events.feature
  features/step_definitions/events_steps.rb
  features/volunteer_opportunities/search_volunteer_opportunities.feature
  spec/controllers/events_controller_spec.rb
  spec/factories.rb
  spec/models/event_spec.rb
Labels: ready-for-merge
